services:
  hono-app:
    container_name: mail-service
    build: .
    ports:
      - "93:3000" # Mengarahkan domain ke port 92
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "bun install && bun run dev"
    environment:
      NODE_ENV: production
